export default [
    {
        link: 'https://igoryakib.github.io/Homeworks/Module%204/',
        img: '../img/mogo4.png',
        name: 'Mogo',
        type: 'website',
        description: 'Mogo is a popular webStudio for development webSite or web-program.',
    },
    {
        link: 'https://igoryakib.github.io/Homeworks/Module%205/',
        img: '../img/mogo5.png',
        name: 'Mogo 2.0',
        type: 'website',
        description: 'Updated version the same previous Mogo but with functionality.', 
    },
    {
        link: 'https://igoryakib.github.io/Homeworks/Module%206/',
        img: '../img/golden6.png',
        name: 'Golden',
        type: 'website',
        description: 'Golden is the same service with Mogo but have different in functionality.',
    },
    {
        link: 'https://igoryakib.github.io/Homeworks/Module%207/',
        img: '../img/module7.png',
        name: 'URLAUBSGLÜCK',
        type: 'website',
        description: 'URLAUBSGLÜCK is a simple landing page with adaptivity on mobile, tablet and desktop device.',
    },
    {
        link: 'https://igoryakib.github.io/HomeworkJS/Module8/',
        img: '../img/module8.png',
        name: 'Gallery',
        type: 'website',
        description: 'Simple web-gallery with Java Script language.',
    },
    {
        link: 'https://memories-factory.github.io/',
        img: '../img/memoriesFactory.png',
        name: 'Memories Factory',
        type: 'website',
        description: 'WebSite - service that work with photos, videos and another.',
    },
    {
        link: 'https://dmytrokolisnyk2.github.io/ubermensches_project/build/',
        img: '../img/brawlStarsSite.png',
        name: 'Brawl Stars Site',
        type: 'website',
        description: 'Landing page about famous mobile game Brawl Stars.',
    },
    {
        link: 'https://dmytrokolisnyk2.github.io/HOPE_project/',
        img: '../img/BrawlStarsGame.png',
        name: 'Brawl Stars Card Game',
        type: 'web-program',
        description: 'It is web-game has created with help Java Script in style Brawl Stars.',  
    },
    {
        link: 'https://dmytrokolisnyk2.github.io/GameOFTeens_JAVASCRIPT/',
        img: '../img/testHope.png',
        name: 'HOPE Test',
        type: 'web-program',
        description: 'It is test which verify your knowing other language programing.',
    },
    {
        link: 'https://dmytrokolisnyk2.github.io/test-hakaton/index.html',
        img: '../img/trelloHope.png',
        name: 'Trello',
        type: 'web-program',
        description: 'Trello. Do you heard about it? It is web-program for planning and for better your productivity.',
    },
    {
        link: 'https://dmytrokolisnyk2.github.io/test-hackathon-2.0/index.html',
        img: '../img/ticTacToeHope.png',
        name: 'Tic Tac Toe',
        type: 'web-program',
        description: 'Tic Tac Toe popular game, that we made in browse.',
    },
    {
        link: 'https://drive.google.com/drive/folders/1wAH_kiUZqV4wfC4dzmSD1a4UIO-92GpI',
        img: '../img/logo.jpg',
        name: 'Design logo 1',
        type: 'design',
        description: 'It is first design logo our team.',
    },
    {
        link: 'https://drive.google.com/drive/folders/1wAH_kiUZqV4wfC4dzmSD1a4UIO-92GpI',
        img: '../img/logo2.jpg',
        name: 'Design logo 2',
        type: 'design',
        description: 'It is second design logo our team.',
    },
    {
        link: 'https://drive.google.com/drive/folders/1wAH_kiUZqV4wfC4dzmSD1a4UIO-92GpI',
        img: '../img/logo3.jpg',
        name: 'Design logo 3',
        type: 'design',
        description: 'It is third design logo our team.',
    },
]